import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Stars from '@/components/sub/Stars'
import Navbar from '@/components/main/Navbar'
import Footer from '@/components/main/Footer'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/saksham_fav.jpg" />
      </Head>
      <body className={`${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden`}>
        <Navbar/>
        <Stars/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
