import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Stars from '@/components/main/Stars'
import About from '@/components/main/About'
import Navbar from '@/components/main/Navbar'
import Contact from '@/components/main/Contact'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden`}>
        <Navbar/>
        <Stars/>
        {children}
      </body>
    </html>
  )
}
